name: Code checks (linting + unit tests)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Run Flake8 Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pandas

      - name: Run flake8
        run: flake8 .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # python-version: '3.9'
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m pip install --upgrade pip
          # pip install pytest pandas

      - name: Run tests
        run: pytest tests/
